# Generated by Django 4.1.1 on 2022-09-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cryptobot_run_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptobot",
            name="execution_type",
            field=models.IntegerField(
                choices=[
                    (0, "Once"),
                    (1, "Weekly"),
                    (2, "Daily"),
                    (3, "Hourly"),
                    (4, "Minute"),
                    (5, "Asap"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="cryptobot",
            name="run_status",
            field=models.IntegerField(
                choices=[(0, "Stopped"), (1, "Running"), (2, "Error")]
            ),
        ),
    ]
