# Generated by Django 4.1.1 on 2022-09-16 11:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_alter_cryptobot_execution_type_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CryptoBot",
            new_name="Bot",
        ),
    ]
