# Generated by Django 4.1.1 on 2022-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_cryptobot_bot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bot",
            name="run_status",
        ),
        migrations.AddField(
            model_name="bot",
            name="container_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
